### ISSUE TITLE
ci: keep failing because of deprecation warning about 3.13

### ISSUE THREAD

**Issue by simkimsia** [torchbox/django-pattern-library#216]
Found a bug? Please fill out the sections below. 👍

### Issue Summary

My PR #213 keeps failing in py311-dj41 

```
py311-dj41: install_package_deps> python -I -m pip install 'Django<4.3,>=3.2' 'Markdown<4.0,>=3.1' 'PyYAML<7.0,>=5.1'
py311-dj41: install_package> python -I -m pip install --force-reinstall --no-deps /home/runner/work/django-pattern-library/django-pattern-library/.tox/.tmp/package/1/django_pattern_library-1.0.0.tar.gz
py311-dj41: freeze> python -m pip freeze --all
py311-dj41: asgiref==3.6.0,Django==4.1,django-pattern-library @ file:///home/runner/work/django-pattern-library/django-pattern-library/.tox/.tmp/package/1/django_pattern_library-1.0.0.tar.gz,Markdown==3.4.3,pip==23.0.1,PyYAML==6.0,setuptools==67.4.0,sqlparse==0.4.3,wheel==0.38.4
py311-dj41: commands[0]> poetry install -q
py311-dj41: commands[1]> poetry run python -X dev -W error runtests.py
Traceback (most recent call last):
  File "/home/runner/work/django-pattern-library/django-pattern-library/runtests.py", line 8, in <module>
    from django.test.utils import get_runner
  File "/home/runner/work/django-pattern-library/django-pattern-library/.tox/py311-dj41/lib/python3.11/site-packages/django/test/__init__.py", line 3, in <module>
    from django.test.client import (
  File "/home/runner/work/django-pattern-library/django-pattern-library/.tox/py311-dj41/lib/python3.11/site-packages/django/test/client.py", line 15, in <module>
    from django.core.handlers.asgi import ASGIRequest
  File "/home/runner/work/django-pattern-library/django-pattern-library/.tox/py311-dj41/lib/python3.11/site-packages/django/core/handlers/asgi.py", line 11, in <module>
    from django.core.handlers import base
  File "/home/runner/work/django-pattern-library/django-pattern-library/.tox/py[31](https://github.com/torchbox/django-pattern-library/actions/runs/4587338906/jobs/8100793513#step:6:32)1-dj41/lib/python3.11/site-packages/django/core/handlers/base.py", line 11, in <module>
    from django.urls import get_resolver, set_urlconf
  File "/home/runner/work/django-pattern-library/django-pattern-library/.tox/py311-dj41/lib/python3.11/site-packages/django/urls/__init__.py", line 1, in <module>
    from .base import (
  File "/home/runner/work/django-pattern-library/django-pattern-library/.tox/py311-dj41/lib/python3.11/site-packages/django/urls/base.py", line 8, in <module>
    from .exceptions import NoReverseMatch, Resolver404
  File "/home/runner/work/django-pattern-library/django-pattern-library/.tox/py311-dj41/lib/python3.11/site-packages/django/urls/exceptions.py", line 1, in <module>
    from django.http import Http404
```

I am pretty sure that Django  4.1 fixed this issue months ago https://code.djangoproject.com/ticket/33173#comment:9

**Comment by simkimsia** [comment]
Closing this since #221 is better
