### ISSUE TITLE
Django >= 2.0 is not supported

### ISSUE THREAD

**Issue by thibaudcolas** [torchbox/django-pattern-library#25]
In GitLab by @bcdickinson on Jan 29, 2019, 11:21

We need to support `Django>=1.11`: https://www.djangoproject.com/download/#supported-versions

Python 3 only.

We should use tox to test across Django versions.

From the tests:

```======================================================================
ERROR: tests.tests.test_context (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.tests.test_context
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/loader.py", line 434, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.7/unittest/loader.py", line 375, in _get_module_from_name
    __import__(name)
  File "/home/bdickinson/Git/Django/django-pattern-library/tests/tests/test_context.py", line 1, in <module>
    from django.core.urlresolvers import reverse
ModuleNotFoundError: No module named 'django.core.urlresolvers'```

**Comment by thibaudcolas** [comment]
In GitLab by @bcdickinson on Feb 2, 2019, 12:11

This turned out just to be a problem with imports in the tests. Resolved by the `tox` branch, which is merged now.

**Comment by thibaudcolas** [comment]
In GitLab by @bcdickinson on Feb 2, 2019, 12:11

closed
